version: '3'
services:
  mysql:
    build:
      context: .
      dockerfile: ./docker-config/mysql/Dockerfile
    ports:
    - '3306:3306'
    volumes:
    - ./data/mysql:/var/lib/mysql
    - ./data/init.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: golang
      MYSQL_DATABASE: golang_echo
      TZ: Asia/Tokyo
  go:
    build:
      context: .
      dockerfile: ./docker-config/go/Dockerfile
    volumes:
      - ./src:/go/src/github.com/KaoruOhbayashi/golang_echo
    depends_on:
      - mysql
    ports:
      - '8080:8080'
